#include <stdio.h>
#include <stddef.h>

struct Student {
    char name[32];
    int id;
};

void print_header(void) {
    printf("==== OS Lab Git Practice ====\n");
}

void print_numbers(int n) {
    printf("Numbers from 1 to %d:\n", n);
    for (int i = 1; i <= n; i++) {
        printf("%d ", i);
    }
    printf("\n");
}

int factorial(int n) {
    if (n < 0) {
        return 0;
    }
    int result = 1;
    for (int i = 2; i <= n; i++) {
        result *= i;
    }
    return result;
}

double average(const int *arr, size_t len) {
    if (len == 0) {
        return 0.0;
    }
    long long sum = 0;
    for (size_t i = 0; i < len; i++) {
        sum += arr[i];
    }
    return (double)sum / (double)len;
}

void print_student(const struct Student *s) {
    printf("Student(name=\"%s\", id=%d)\n", s->name, s->id);
}

int main(int argc, char *argv[]) {
    print_header();
    print_numbers(5);

    int n = 5;
    int fact = factorial(n);
    printf("factorial(%d) = %d\n", n, fact);

    int scores[] = {80, 90, 75, 95};
    double avg = average(scores, sizeof(scores) / sizeof(scores[0]));
    printf("average score = %.2f\n", avg);

    struct Student s = {"OSLab", 25200000};
    print_student(&s);

    if (argc > 1) {
        printf("First argument: %s\n", argv[1]);
    } else {
        printf("No arguments given.\n");
    }

    FILE *fp = fopen("oslab_output.txt", "w");
    if (fp != NULL) {
        fprintf(fp, "This file was generated by oslab_practice.c\n");
        fprintf(fp, "average = %.2f\n", avg);
        fclose(fp);
        printf("Wrote oslab_output.txt\n");
    } else {
        printf("Failed to open oslab_output.txt for writing.\n");
    }

    return 0;
}
